### PR TITLE
deps: update eslint to v10 and neostandard to 0.14.0-next.1

### PR DESCRIPTION
**Pull request by marcopiraccini**
## What

Updates `eslint` to v10 and `neostandard` to `0.14.0-next.1`.

Supersedes #218, which bumped only `eslint` and cannot go green on its own.

## Why #218 fails

eslint 10 removed the `SourceCode#isSpaceBetweenTokens` API. `neostandard@0.13.0` (current `latest`) bundles `@stylistic/eslint-plugin@2.11.0`, which still calls it, so the lint step crashes on the first file:

```
TypeError: sourceCode.isSpaceBetweenTokens is not a function
Rule: "@stylistic/space-in-parens"
  at @stylistic/eslint-plugin@2.11.0/dist/rules/space-in-parens.js
```

The underlying problem is a peer conflict: `neostandard@0.13.0` declares `peerDependencies: { eslint: "^9.0.0" }`, so eslint 10 cannot be satisfied. That is also why the `renovate/artifacts` check on #218 reported "Artifact file update failure" - renovate could not regenerate the lockfile, leaving the PR with only a `package.json` change.

## The fix

`neostandard@0.14.0-next.1` declares `peerDependencies: { eslint: "^9.22.0 || ^10.0.0" }` and pulls `@stylistic/eslint-plugin@5.10.0`, which is eslint 10 compatible. Bumping both together resolves the peer conflict.

Note: `0.14.0-next.1` is a prerelease (`next` dist-tag); stable `latest` is still `0.13.0`, which does not support eslint 10. Pinned exactly rather than range-matched for that reason.

## Verification

Run locally on Node 24 with the new versions:

- `pnpm install --frozen-lockfile` - exit 0, no peer warnings
- `pnpm run test` (lint + full suite) - exit 0
- Lint clean, tests **129/129 pass, 0 fail**

No source or test changes were needed; this is dependencies only.

### CODE REVIEW

**Review by leorossi — APPROVED** [review]
LGTM
